### ISSUE TITLE
Rebuild .tar.gz files every commit

### ISSUE THREAD

**Issue by sarina** [openedx/openedx-test-course#7]
## Background

In order to make this course widely-available to everyone, including course teams and instance operators, we are adding .tar.gz course & library bundles that anyone can download and import into their instance.

See: < PR >

## Tasks

Do one or both of these:
- [ ] Add a GitHub action that re-builds these files every commit.
- [ ] Add a CI check that ensures the .tar.gz files are not outdated.

**Comment by kdmccormick** [comment]
~@sarina This fixes the build, could you review? In the meantime I'm working on https://github.com/openedx/openedx-test-course/pull/8~

**Comment by kdmccormick** [comment]
^ Sorry, wrong issue
